version: "3.1"

# Configuration for Rasa NLU.
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200 # Increase training epochs for better accuracy
    constrain_similarities: true # Prevents similar responses being matched
  - name: FallbackClassifier
    threshold: 0.4 # Increase threshold for fallback intent
    ambiguity_threshold: 0.1 # Better handles overlapping intents

# Configuration for Rasa Core.
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
assistant_id: 20241205-164923-cyan-nectarine
