audio_file_map = {
    "agent #1 (1).wav": "Agent #1 (1).wav",
    "agent #1 (2).wav": "Agent #1 (2).wav",
    "agent #1 (3).wav": "Agent #1 (3).wav",
    "agent #1 (4 ai).wav": "Agent #1 (4 AI).wav",
    "agent #1 (4 artificial intelligence).wav": "Agent #1 (4 artificial intelligence).wav",
    "agent #1 (4 automotive).wav": "Agent #1 (4 automotive).wav",
    "agent #1 (4 ecommerce).wav": "Agent #1 (4 ecommerce).wav",
    "agent #1 (4 education).wav": "Agent #1 (4 education).wav",
    "agent #1 (4 farming).wav": "Agent #1 (4 farming).wav",
    "agent #1 (4 fashion).wav": "Agent #1 (4 fashion).wav",
    "agent #1 (4 food).wav": "Agent #1 (4 food).wav",
    "agent #1 (4 healthcare).wav": "Agent #1 (4 healthcare).wav",
    "agent #1 (4 home services).wav": "Agent #1 (4 home services).wav",
    "agent #1 (4 insurance).wav": "Agent #1 (4 insurance).wav",
    "agent #1 (4 manufacturing).wav": "Agent #1 (4 manufacturing).wav",
    "agent #1 (4 medical).wav": "Agent #1 (4 medical).wav",
    "agent #1 (4 real estate).wav": "Agent #1 (4 real estate).wav",
    "agent #1 (4 technology).wav": "Agent #1 (4 technology).wav",
    "agent #1 (4 telecommunications).wav": "Agent #1 (4 telecommunications).wav",
    "agent #1 (4 transportation).wav": "Agent #1 (4 transportation).wav",
    "agent #1 (4 yoga).wav": "Agent #1 (4 yoga).wav",
    "agent #1 (5).wav": "Agent #1 (5).wav",
    "agent #1 (6).wav": "Agent #1 (6).wav",
    "agent #1 (7).wav": "Agent #1 (7).wav",
    "agent #1 (8).wav": "Agent #1 (8).wav",
    "agent #1 (9).wav": "Agent #1 (9).wav",
    "agent #1 (11).wav": "Agent #1 (11).wav",
    "agent #1 (12).wav": "Agent #1 (12).wav",
    "agent #1 (13).wav": "Agent #1 (13).wav",
    "agent #1 (14).wav": "Agent #1 (14).wav",
    "agent #1 (15).wav": "Agent #1 (15).wav",
    "agent #1 (16).wav": "Agent #1 (16).wav",
    "agent #1 (17).wav": "Agent #1 (17).wav",
    "agent #1 (18).wav": "Agent #1 (18).wav",
    "agent #1 (19).wav": "Agent #1 (19).wav",
    "agent #1 (21).wav": "Agent #1 (21).wav",
    "agent #1 (23 animation).wav": "Agent #1 (23 animation).wav",
    "agent #1 (23 branding).wav": "Agent #1 (23 branding).wav",
    "agent #1 (23 digital marketing).wav": "Agent #1 (23 digital marketing).wav",
    "agent #1 (23 email marketing).wav": "Agent #1 (23 email marketing).wav",
    "agent #1 (23 mobile app development).wav": "Agent #1 (23 mobile app development).wav",
    "agent #1 (23 virtual assistance).wav": "Agent #1 (23 virtual assistance).wav",
    "agent #1 (23 web design).wav": "Agent #1 (23 web design).wav",
    "agent #1 (23 web development).wav": "Agent #1 (23 web development).wav",
    "agent #1 (24).wav": "Agent #1 (24).wav",
    "agent #1 (25).wav": "Agent #1 (25).wav",
    "agent #1 (28 sample 1).wav": "Agent #1 (28 sample 1).wav",
    "agent #1 (28 sample 2).wav": "Agent #1 (28 sample 2).wav",
    "agent #1 (28 sample 3).wav": "Agent #1 (28 sample 3).wav",
    "agent #1 (29).wav": "Agent #1 (29).wav",
    "1. sorry, what was that_.wav": "1. Sorry, what was that_.wav",
    "2. say that again_.wav": "2. Say that again_.wav",
    "3. i didn’t catch that..wav": "3. I didn’t catch that..wav",
    "4. sorry, one more time_.wav": "4. Sorry, one more time_.wav",
    "5. what was that_.wav": "5. What was that_.wav",
    "6. i missed that..wav": "6. I missed that..wav",
    "7. pardon me_.wav": "7. Pardon me_.wav",
    "gatekeepers 1.wav": "Gatekeepers 1.wav",
    "gatekeepers 2.wav": "Gatekeepers 2.wav",
    "gatekeepers 3.wav": "Gatekeepers 3.wav",
    "gatekeepers _ (row 33).wav": "Gatekeepers _ (row 33).wav",
    "incoming call voicemail box message (rebuttals 4g).wav": "Incoming call voicemail box message (Rebuttals 4G).wav",
    "voicemail drop (rebuttals 4c).wav": "Voicemail drop (Rebuttals 4C).wav",
    "q1 rebuttals 1, 2, 4, 6, 7 (row 19).wav": "Q1 rebuttals 1, 2, 4, 6, 7 (row 19).wav",
    "q1 rebuttals 3 (row 21).wav": "Q1 rebuttals 3 (row 21).wav",
    "q1 rebuttals 5 (row 23).wav": "Q1 rebuttals 5 (row 23).wav",
    "q1 rebuttals 8 (row 26).wav": "Q1 rebuttals 8 (row 26).wav",
    "q1 rebuttals 9&10 (row 27).wav": "Q1 rebuttals 9&10 (row 27).wav",
    "1. sony47821.com.wav": "1. sony47821.com.wav",
    "2. bcraccounting.com.wav": "2. bcraccounting.com.wav",
    "3. yummy-cookies.com.wav": "3. yummy-cookies.com.wav",
    "4. burbys.com.wav": "4. burbys.com.wav",
    "5. wbrf.com.wav": "5. wbrf.com.wav",
    "6. 24-7auto.com.wav": "6. 24-7auto.com.wav",
    "7. kprmusic.org.wav": "7. kprmusic.org.wav",
    "8. klaxxon.edu.wav": "8. klaxxon.edu.wav",
    "9. fbi.gov.wav": "9. fbi.gov.wav",
    "10. google.us.wav": "10. google.us.wav",
    "q 3&4 rebuttals 1.wav": "Q 3&4 rebuttals 1.wav",
    "q 3&4 rebuttals 2.wav": "Q 3&4 rebuttals 2.wav",
    "q 3&4 rebuttals 3.wav": "Q 3&4 rebuttals 3.wav",
    "q 3&4 rebuttals 4.wav": "Q 3&4 rebuttals 4.wav",
    "q 3&4 rebuttals 5.wav": "Q 3&4 rebuttals 5.wav",
    "q 3&4 rebuttals 6.wav": "Q 3&4 rebuttals 6.wav",
    "q 3&4 rebuttals 7.wav": "Q 3&4 rebuttals 7.wav",
    "q 3&4 rebuttals 8.wav": "Q 3&4 rebuttals 8.wav",
    "q 3&4 rebuttals 9 (beginning and if yes).wav": "Q 3&4 rebuttals 9 (beginning and IF YES).wav",
    "q 3&4 rebuttals 9 (if no).wav": "Q 3&4 rebuttals 9 (IF NO).wav",
    "q 3&4 rebuttals 10.wav": "Q 3&4 rebuttals 10.wav",
    "q 3&4 rebuttals 11.wav": "Q 3&4 rebuttals 11.wav",
    "q 3&4 rebuttals 12.wav": "Q 3&4 rebuttals 12.wav",
    "q 3&4 rebuttals 13.wav": "Q 3&4 rebuttals 13.wav",
    "q 3&4 rebuttals 14 part 1(if yes, if website and if marketing).wav": "Q 3&4 rebuttals 14 part 1(IF YES, IF WEBSITE and IF MARKETING).wav",
    "q 3&4 rebuttals 14 part 2(if multiple).wav": "Q 3&4 rebuttals 14 part 2(IF MULTIPLE).wav",
    "q 3&4 rebuttals 15.wav": "Q 3&4 rebuttals 15.wav",
}